# Análise de Dados
#Base de Dados referente a: Hashtag Treinamentos

In [2]:
#Importar a Biblioteca
import pandas as pd

#Visualizar Base de Dados
vendas_df = pd.read_excel('Vendas-dez.xlsx')
vendas_df.head()

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,65014,2019-12-01,Shopping Morumbi,Sunga Listrado,5,114,570
1,65014,2019-12-01,Shopping Morumbi,Casaco Listrado,1,269,269
2,65016,2019-12-01,Iguatemi Campinas,Sapato Listrado,2,363,726
3,65016,2019-12-01,Iguatemi Campinas,Casaco,1,250,250
4,65017,2019-12-01,Shopping SP Market,Gorro Liso,3,92,276

In [ ]:
#Quantidade de transações por loja (shopping) OK
#Mostra a tabela de acordo com a escolha da Loja (Shopping)
#Faturamento por loja (shopping) OK
#Buscar a média de QUANTIDADE por compra dos Shoppings
#Saber a média da QUANTIDADE por shopping determinado

In [20]:
#Quantidade de transações por loja (Shopping)
transacoes = vendas_df['ID Loja'].value_counts()
print(transacoes)

Rio Mar Recife                      366
Iguatemi Campinas                   315
Shopping Morumbi                    306
Shopping Eldorado                   304
Salvador Shopping                   302
Palladium Shopping Curitiba         301
Center Shopping Uberlândia          300
Shopping Vila Velha                 299
Rio Mar Shopping Fortaleza          294
Shopping Iguatemi Fortaleza         290
Parque Dom Pedro Shopping           290
Passei das Águas Shopping           289
Bourbon Shopping SP                 286
Shopping Recife                     286
Shopping União de Osasco            284
Ribeirão Shopping                   277
Shopping Ibirapuera                 273
Shopping SP Market                  272
Shopping Barra                      260
Shopping Midway Mall                259
Iguatemi Esplanada                  258
Norte Shopping                      255
Shopping Center Interlagos          254
Novo Shopping Ribeirão Preto        239
Shopping Center Leste Aricanduva    230
Name: ID Loja, dtype: int64

In [35]:
#Mostra a tabela de acordo com a escolha da Loja (Shopping)

vendas_rmar_rec = vendas_df.loc[vendas_df['ID Loja'] == 'Rio Mar Recife', ['ID Loja', 'Produto', 'Valor Final']]
print(vendas_rmar_rec)

             ID Loja               Produto  Valor Final
28    Rio Mar Recife                 Calça          170
52    Rio Mar Recife  Camisa Gola V Xadrez          214
110   Rio Mar Recife        Bermuda Xadrez          465
111   Rio Mar Recife        Calça Listrado          181
112   Rio Mar Recife         Casaco Xadrez          259
...              ...                   ...          ...
6948  Rio Mar Recife      Mochila Listrado          550
6949  Rio Mar Recife         Camisa Xadrez          315
6950  Rio Mar Recife            Tênis Liso          798
7019  Rio Mar Recife               Chinelo          180
7020  Rio Mar Recife       Casaco Listrado          807

[366 rows x 3 columns]

In [26]:
#Faturamento por Loja (Shopping)
faturamento = vendas_df[['ID Loja', 'Valor Final']].groupby('ID Loja').sum()
display(faturamento)

                                  Valor Final
ID Loja
Bourbon Shopping SP                    125850
Center Shopping Uberlândia             124960
Iguatemi Campinas                      149959
Iguatemi Esplanada                     103342
Norte Shopping                         101491
Novo Shopping Ribeirão Preto            99703
Palladium Shopping Curitiba            120621
Parque Dom Pedro Shopping              122055
Passei das Águas Shopping              112089
Ribeirão Shopping                      112936
Rio Mar Recife                         139869
Rio Mar Shopping Fortaleza             127890
Salvador Shopping                      129156
Shopping Barra                         103148
Shopping Center Interlagos             103821
Shopping Center Leste Aricanduva        86156
Shopping Eldorado                      124339
Shopping Ibirapuera                    107907
Shopping Iguatemi Fortaleza            124182
Shopping Midway Mall                   105269
Shopping Morumbi                       117936
Shopping Recife                        131871
Shopping SP Market                     110833
Shopping União de Osasco               116032
Shopping Vila Velha                    115896